name: Release ecsctl

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  create-release:
    permissions:
      contents: write  # Required for creating releases
    needs: [build-and-test]  # Only needed for tag pushes
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ecsctl-linux/ecsctl-linux
            ecsctl-macos/ecsctl-macos
          draft: false
          prerelease: false 